project:
  type: website
  output-dir: docs  

website:
  title: "Mapping NHS Data Architecture and Flows"
  navbar:
    background: secondary
  sidebar: 
    style: "docked"
    search: false
    contents:
        - section: "MAIN"
          contents: 
            - href: index.qmd
              text: Introduction
        - section: "NATIONAL"
          contents: 
            - href: main.qmd
              text: National diagram

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
