project:
  type: website
  output-dir: docs  

website:
  title: "NHS Data Architecture & Data Flows"
  navbar:
    background: secondary
  sidebar: 
    style: "docked"
    search: false
    contents:
        - section: "MAIN"
          contents: 
            - href: index.qmd
              text: Introduction       
        - section: "NATIONAL"
          contents: 
            - href: national/main.qmd
              text: National schematic
            - href: national/sources.qmd
              text: Data sources
            - href: national/flows.qmd
              text: Data flow categories
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
