project:
  type: website
  output-dir: docs  

website:
  title: "NHS Data Architecture"
  navbar:
    background: secondary
  sidebar: 
    style: "docked"
    search: false
    contents:
      - href: index.qmd
      - href: main.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
