---
title: "Summary of Data Flows"
---

_Early preview v0.1_

This page contains an overview of the broad classifications of data flow from the main schematic. At present, national data architectures make a clear division between data for direct care (top half of schematic) and other secondary uses (bottom half of schematic).

### Direct Care

#### NHS Spine

The [NHS Spine](https://digital.nhs.uk/services/spine) pulls in core clinical data from various NHS systems, including GP practices, hospitals, and other care settings, to provide a national source of truth for the most vital patient information. Components include: 

- [Personal Demographics Service (PDS)](https://digital.nhs.uk/services/personal-demographics-service), serving as a central, authoritative source of patient demographic information with each patient identified through an NHS number. Patient records can be updated through primary and secondary care software, and it serves as a master patient index for other digital systems or for analytics.      
- [Summary Care Record (SCR)](https://digital.nhs.uk/services/summary-care-records-scr), containing key clinical information such as allergies, medications, and adverse reactions. This data is sourced primarily from GP systems and is used to support direct patient care across different NHS settings, ensuring that essential information is always available to clinicians when needed.
- [Electronic Prescription Service](https://digital.nhs.uk/services/electronic-prescription-service) allows prescriptions from primary, community, and hospitals to be sent to pharmacies that dispense medications.

#### Shared care records

Shared Care Records (or Health Information Exchange (HIE)) integrates patient data from multiple care settings within a local health and care system. Data is typically shared between GP practices, hospitals, community services, mental health providers, and social care. This can include demographic information, diagnoses, medications, care plans, and recent encounters. The purpose is to provide a more comprehensive view of a patient's health and care history to support care delivery occurring across multiple physical locations. A fuller view of how Shared Care Records have evolved in the NHS can be found [here](https://www.nature.com/articles/s41746-023-00891-y).  

#### NHS App

The [NHS App](https://digital.nhs.uk/services/nhs-app/nhs-app-features) serves as a patient-facing portal that both various types of data, and provides services directly to patients. It interfaces with GP systems to allow patients to book appointments and order repeat prescriptions. It also pulls in data from GP systems and the NHS Spine to enable patients to view their medical records. Additionally, it may integrate with referral systems to enable patients to view their hospital referral and appointment statuses, and average waiting times.

### Other Uses

#### GP data (NHS and other) extractions

Primary care systems in the NHS (EMIS, TPP, Vision) offer an Application Programming Interface (API) which allows interface with the clinical system, and bulk extraction of patient data. This data can include most data tables within the source systems, including diagnosis codes, prescriptions, referrals, test results, and demographic information. This data extraction is used to support numerous secondary uses including population health, service planning, and research. Extractors include NHS organisations, as well as large research databases who offer access to collected data for consumers, and companies who may provide analytical services and products built on the data.  

#### Births & deaths

Births and deaths are reported through established systems of forms and submissions to the level of registration districts. Records here are collated upwards to the General Register Office who hold national records for births and deaths, as well as marriages and civil partnerships. The Office of National Statistics uses this to create the analysis-ready [Civil Registrations of Death](https://digital.nhs.uk/services/data-access-request-service-dars/dars-products-and-services/data-set-catalogue/civil-registrations-of-death) dataset, that provides patient outcomes that join onto other datasets. 

#### NHS Digital submissions

Secondary care data related to patient attendances, diagnoses, and procedures,  are largely found within free text in source systems. These are captured through a process of clinical coding, by teams of specialised coders in each hospital, who read through patient records and record the most important information relevant for each episode. This is turned into data tables (e.g. [Secondary Uses Service](https://digital.nhs.uk/services/secondary-uses-service-sus)), and submitted to the NHS through a standard system, where data is used both for reimbursements, and for creating analysis datasets (such as the [Hospital Episode Statistics](https://digital.nhs.uk/data-and-information/data-tools-and-services/data-services/hospital-episode-statistics)). Data for analysis and linkage to other sources are made available through the [Data Access Request Service (DARS)](https://digital.nhs.uk/services/data-access-request-service-dars).      

#### National Disease Registration Service

The [National Disease Registration Service (NDRS)](https://digital.nhs.uk/ndrs/) collects data on specific diseases and conditions, primarily cancer and rare diseases. Data is collected in hospitals through a mixture of manual abstraction and coding (typically by cancer audit teams), or by automated extraction from EHR systems (such as chemotherapy prescribing systems). The resulting datasets include the [Cancer Outcomes and Services Dataset (COSD)](https://digital.nhs.uk/ndrs/data/data-sets/cosd), and the [Systemic Anti-Cancer Therapies dataset (SACT)](https://digital.nhs.uk/ndrs/data/data-sets/sact). Data is used for audit purposes, but also as a research and analytics resource, by being made available through the [Data Access Request Service (DARS)](https://digital.nhs.uk/services/data-access-request-service-dars). 

#### NHS Digitrials

This is a [national platform](https://digital.nhs.uk/services/nhs-digitrials) that allows organisations conducting clinical trials to discover and recruit patients that fit research inclusion criteria. Such criteria usually includes demographic information, as well as data about diagnoses and medications. The Digitrials platform is able to pull data from the Personal Demographics Service, as well as access hospital diagnosis data (via Hospital Episode Statistics), and medication dispensing data.

### Version history

_version 0.1 24-08-05: first version of key data flows_